
package casa;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;



public class NewJPanel extends javax.swing.JPanel {

    
    public NewJPanel() {
        initComponents();
        
    }
   
    float pu;
    Color C=(Color.BLACK);
    int c1,c2;
public void paintComponent(Graphics g) {
    Casita a=new Casita();
 super.paintComponent(g);
 Graphics2D g2 = (Graphics2D)g;
 Graphics2D VENT1 = (Graphics2D)g;
 Graphics2D VENT2 = (Graphics2D)g;
 Graphics2D PUERTA = (Graphics2D)g;
 Graphics2D L = (Graphics2D)g;
 Color n=new Color(237,185,95);
 Color s=new Color(124,80,4);
 g2.setColor(n);
 g2.setStroke(new BasicStroke(3.0f));
 Rectangle2D r = new Rectangle2D.Float(100.0f, 100.0f, 250.0f, 250.0f);
 g2.fill(r);
 g2.draw(r);
 
 VENT1.setColor(C);
 VENT1.setStroke(new BasicStroke(3.0f));
 Rectangle2D r2 = new Rectangle2D.Float(150.0f, 150.0f, 50.0f, 50.0f);
 VENT1.fill(r2);
 VENT1.draw(r2);
 
 VENT2.setColor(C);
 VENT2.setStroke(new BasicStroke(3.0f));
 Rectangle2D r3 = new Rectangle2D.Float(250.0f, 150.0f, 50.0f, 50.0f);
 VENT2.fill(r3);
 VENT2.draw(r3);
 
 g2.setColor(Color.BLACK);
 Rectangle2D r5 = new Rectangle2D.Float(200.0f, 250.0f, 50.0f,100.0f);
 g2.fill(r5);
 g2.draw(r5);
 
 
 g2.setColor(Color.GREEN);
 g2.drawLine(0, 350, 500, 350);
 
 PUERTA.setColor(Color.getHSBColor(153, 102, 60));
 int xs[]={200,250-c1,250-c1,200};
 int ys[]={250,250+c1,350+c1,350};
 PUERTA.fillPolygon(xs, ys, 4);
 /*PUERTA.setColor(Color.getHSBColor(153, 102, 60));
 PUERTA.setStroke(new BasicStroke(3.0f));
 PUERTA.setBackground(Color.RED);
 Rectangle2D r4 = new Rectangle2D.Float(200.0f, 250.0f, 50.0f+pu,100.0f);
 PUERTA.fill(r4);
 PUERTA.draw(r4);*/


L.setColor(s);
int xPoints[]={50,100,350,400};
int yPoints[]={100,50,50,100};
L.drawPolygon(xPoints,yPoints,4);
//L.setColor(Color.DARK_GRAY);
L.fillPolygon(xPoints,yPoints,4);



}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
